# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[34,)" #mandatory (34 is current forge version)  This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.


license="All Rights Reserved"  #mandatory

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/cleverpanda/SimpleCabbage/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId="simplecabbage" #mandatory

# The version number of the mod - "there's a few well known ${} variables useable here or just hardcode it" (Not well known by me, but hey)
# Digging into the source (StringSubstitutor.class) I think the valid variables are currently (Forge 1.14.4-28.1.0):
# ${global.mcVersion}, ${global.forgeVersion}, {$file.jarVersion}
# {$file.xxxxx} where xxxxx is a property you have defined elsewhere in the mods.toml file using a table named as [properties]  - see https://github.com/toml-lang/toml
version="${file.jarVersion}" # mandatory.  {$file.jarVersion} copies the version number from the manifest specification, which is set in the build.gradle file.

 # A display name for the mod
displayName="Simple Cabbage" #mandatory

# A URL to query for updates for this mod. See the JSON update specification here:  https://mcforge.readthedocs.io/en/latest/gettingstarted/autoupdate/
#   updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://github.com/cleverpanda/SimpleCabbage" #optional

# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo.png" #optional

# A text field displayed in the mod UI
authors="Cleverpanda714" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
Cabbage that integrates seamlessly with vanilla Minecraft'''
